package={ name='vulkano-spirv', version='0.0.0', edition='2024', description='Macro for generating Vulkano interface for SPIR-V shaders'}
lib={ proc-macro=true }
dependencies={ bytemuck='*', syn='*', vulkano={git='https://github.com/vulkano-rs/vulkano', default-features=false} }
